"""Fresh-process Phase 1 PostgreSQL/Qdrant read-back and evidence finalization."""
import argparse
import asyncio
import json
from pathlib import Path
import sys
import uuid
from datetime import datetime, timezone

REPO=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(REPO/"backend"))
from app.core.config import get_settings
from app.infrastructure.database import init_database, get_async_db, close_database_connections
from app.models.transcript import Transcript, TranscriptSegment
from app.models.meeting import Meeting
from sqlalchemy import select
import app.models

NA="NOT AVAILABLE"
def save(path,value): path.write_text(json.dumps(value,indent=2,default=str),encoding="utf-8")

async def readback(run, mark_failed=False):
    from app.infrastructure.database import Base
    execution=json.loads((run/"execution.json").read_text())
    result={"timestamp":datetime.now(timezone.utc).isoformat(),"fresh_process":True,"status":"NOT VERIFIED"}
    if not execution.get("meeting_id"):
        result["error"]="No meeting ID generated by production CLI"
        save(run/"fresh_readback.json",result)
        return result
    meeting_id=uuid.UUID(execution["meeting_id"])
    init_database()
    try:
        async for session in get_async_db():
            meeting=await session.get(Meeting,meeting_id)
            if mark_failed and meeting:
                calls=json.loads((run/'moss_calls.json').read_text())
                if not any(c.get('status')=='FAILED' and 'out of memory' in c.get('error','').lower() for c in calls):
                    raise RuntimeError('Refusing failure-state update without actual CUDA OOM evidence')
                meeting.status='failed'
                meeting.settings={**(meeting.settings or {}),'phase1_validation':{
                    'run_id':execution['run_id'],'status':'BLOCKED','reason':'Observed CUDA OOM; validation process stopped to prevent identical retries'}}
                await session.commit()
                await session.refresh(meeting)
                result['failure_state_committed']=True
            result["meeting_status"]=meeting.status if meeting else NA
            result["meeting_settings"]=meeting.settings if meeting else {}
            canonical=(await session.execute(select(Transcript).where(Transcript.meeting_id==meeting_id).order_by(Transcript.version.desc()))).scalars().first()
            segments=(await session.execute(select(TranscriptSegment).where(TranscriptSegment.meeting_id==meeting_id).order_by(TranscriptSegment.sequence_number))).scalars().all()
            result["segments"]=[{"id":str(s.id),"speaker":s.speaker_label,"text":s.original_text,
                "start_time_ms":s.start_time_ms,"end_time_ms":s.end_time_ms,"confidence":s.confidence,
                "language":s.language,"sequence_number":s.sequence_number} for s in segments]
            result["canonical_transcript_id"]=str(canonical.id) if canonical else NA
            result["canonical_transcript"]={"full_text":canonical.full_text,"provenance":canonical.provenance} if canonical else NA
            records={}
            indexed=[]
            for table in Base.metadata.sorted_tables:
                if "meeting_id" not in table.c or "id" not in table.c: continue
                cols=[table.c.id]
                if "qdrant_point_id" in table.c: cols.append(table.c.qdrant_point_id)
                if "qdrant_point_id" in table.c and "content" in table.c: cols.append(table.c.content)
                rows=(await session.execute(select(*cols).where(table.c.meeting_id==meeting_id))).mappings().all()
                records[table.name]=[{k:str(v) if isinstance(v,uuid.UUID) else v for k,v in row.items()} for row in rows]
                for row in rows:
                    if row.get("qdrant_point_id"):
                        indexed.append(dict(row))
            result["database_record_ids"]=records
            expected_path=run/"cli_result.json"
            if expected_path.exists() and canonical and segments:
                cli=json.loads(expected_path.read_text())
                expected=cli.get("transcript_segments",[])
                signature=lambda rows:[(s["start_time_ms"],s["end_time_ms"],s["text"],s["speaker"]) for s in rows]
                result["cli_transcript_matches"]=signature(expected)==signature(result["segments"])
                result["canonical_matches_segments"]=canonical.full_text==" ".join(s.original_text for s in segments)
                metadata=(canonical.provenance or {}).get("model",{})
                chunks=metadata.get("chunks",[])
                result["persisted_chunks"]=chunks
                result["chunk_metadata_persisted"]=len(chunks)>1 and all(c.get("status")=="completed" for c in chunks)
                result["status"]="PASSED" if all((result["cli_transcript_matches"],result["canonical_matches_segments"],result["chunk_metadata_persisted"])) else "NOT VERIFIED"
            else:
                result["error"]="No completed CLI transcript/canonical/segments to read back"
            if indexed:
                from app.skw.indexing.semantic_indexer import SemanticIndexer
                indexer=SemanticIndexer()
                client=await indexer._get_client()
                points=await client.retrieve(collection_name=indexer.collection_name,ids=[r["qdrant_point_id"] for r in indexed],with_payload=True,with_vectors=True)
                by_id={str(p.id):p for p in points}
                result["qdrant"]=[{"point_id":r["qdrant_point_id"],"exists":str(r["qdrant_point_id"]) in by_id,
                    "payload_content_matches":str(r["qdrant_point_id"]) in by_id and by_id[str(r["qdrant_point_id"])].payload.get("content")==r.get("content"),
                    "embedding_model":by_id[str(r["qdrant_point_id"])].payload.get("embedding_model") if str(r["qdrant_point_id"]) in by_id else NA} for r in indexed]
            else: result["qdrant"]=NA
            break
    except Exception as exc:
        from app.cli import sanitize_error_text
        result.update(status="NOT VERIFIED",error=sanitize_error_text(str(exc)))
    finally:
        await close_database_connections()
    save(run/"fresh_readback.json",result)
    return result

def finalize(run,read):
    execution=json.loads((run/"execution.json").read_text())
    records=[]
    def walk(value,path,file):
        if isinstance(value,dict):
            for k,v in value.items(): walk(v,path+"."+k,file)
        elif isinstance(value,list):
            for i,v in enumerate(value): walk(v,path+f"[{i}]",file)
        elif isinstance(value,str):
            try: uuid.UUID(value)
            except (ValueError,AttributeError): return
            records.append({"id":value,"field":path,"artifact":file})
    for file in run.glob("*.json"):
        if file.name in ("identifiers.json","phase1_result.json"): continue
        walk(json.loads(file.read_text()),"",file.name)
    events=json.loads((run/"redis_events.json").read_text()) if (run/"redis_events.json").exists() else []
    correlations=sorted({r["id"] for r in records if "correlation_id" in r["field"]})
    ids={"run_id":execution["run_id"],"meeting_id":execution.get("meeting_id",NA),
        "canonical_transcript_id":read.get("canonical_transcript_id",NA),"project_id":execution.get("project_id",NA),
        "chunk_ids":sorted({r["id"] for r in records if "chunk_id" in r["field"]}),
        "correlation_ids":correlations or NA,
        "event_ids":sorted({r["id"] for r in records if "event_id" in r["field"]}) or NA,
        "query_id":NA,"notification_id":NA,"benchmark_run_id":NA,"benchmark_sample_id":NA,
        "redis_stream_id":NA,"knowledge_object_ids":sorted({r["id"] for r in records if "knowledge_id" in r["field"]}) or NA,
        "qdrant_point_ids":[p["point_id"] for p in read.get("qdrant",[]) ] if isinstance(read.get("qdrant"),list) else NA,
        "database_record_ids":read.get("database_record_ids",NA),"git_commit":execution["git_commit"],
        "timestamp":datetime.now(timezone.utc).isoformat(),"all_observed_uuid_fields":records,
        "artifact_paths":[str(f.relative_to(REPO)) for f in run.iterdir() if f.is_file()]}
    save(run/"identifiers.json",ids)
    moss=json.loads((run/"moss_calls.json").read_text()) if (run/"moss_calls.json").exists() else []
    pyannote=json.loads((run/"pyannote.json").read_text()) if (run/"pyannote.json").exists() else {}
    reconstruction=json.loads((run/"speaker_reconciliation.json").read_text()) if (run/"speaker_reconciliation.json").exists() else {}
    offsets=[]
    local={s['segment_id']:(c.get('chunk',{}).get('start_time',0),s) for c in moss for s in c.get('segments',[])}
    for chunk in reconstruction.get('inputs',[]):
        for segment in chunk['global_segments']:
            source=local.get(segment['segment_id'])
            offsets.append({'segment_id':segment['segment_id'], 'matches_local_plus_chunk_start':bool(source) and
                abs(segment['start_time']-round(source[0]+source[1]['start_time'],3))<1e-6 and
                abs(segment['end_time']-round(source[0]+source[1]['end_time'],3))<1e-6})
    persisted=read.get('segments',[])
    math={'step_matches':execution['step']==execution['chunk_duration']-execution['overlap'],
        'valid_overlap':0<execution['overlap']<execution['chunk_duration'],
        'coverage_has_no_gaps':not execution['coverage_has_gaps'],
        'offsets':offsets, 'all_offsets_match':bool(offsets) and all(s['matches_local_plus_chunk_start'] for s in offsets),
        'chronological':bool(persisted) and all(a['start_time_ms']<=b['start_time_ms'] for a,b in zip(persisted,persisted[1:])),
        'bounds_valid':bool(persisted) and all(0<=s['start_time_ms']<s['end_time_ms']<=round(execution['audio_duration']*1000) for s in persisted)}
    save(run/'timestamp_validation.json',math)
    gates={"real_mode":execution["execution_mode"]=="REAL",
        "all_chunks_moss":len(moss)==len(execution["coverage"]) and all(c["status"]=="COMPLETED" for c in moss),
        "pyannote":pyannote.get("status")=="COMPLETED", "persisted_chunk_metadata":read.get("chunk_metadata_persisted",False),
        "cross_chunk_reconciliation":len(reconstruction.get('inputs',[]))>1 and bool(reconstruction.get('mapping')),
        "timestamps":math['all_offsets_match'] and math['chronological'] and math['bounds_valid'],
        "deduplication_executed":(run/"deduplication.json").exists(),
        "fresh_readback":read["status"]=="PASSED", "cli":execution.get("cli_exit_code")==0 and execution.get("final_segment_count",0)>0,
        "redis_distributed":bool(events) and all(e["delivery_status"]=="distributed" for e in events),
        "qdrant":isinstance(read.get("qdrant"),list) and bool(read["qdrant"]) and all(p["exists"] and p["payload_content_matches"] for p in read["qdrant"])}
    failed_moss=next((c.get('error') for c in moss if c.get('status')=='FAILED'),None)
    first_error=failed_moss or execution.get('first_failure') or execution.get('error',NA)
    resource_blocked=any(word in str(first_error).lower() for word in ('out of memory','cuda oom','insufficient vram'))
    result={"phase":1,"status":"VERIFIED" if all(gates.values()) else ('BLOCKED' if resource_blocked else "NOT VERIFIED"),"gates":gates,
        "run_id":execution["run_id"],"meeting_id":execution.get("meeting_id",NA),"canonical_transcript_id":ids["canonical_transcript_id"],
        "correlation_ids":ids["correlation_ids"],"chunk_ids":ids["chunk_ids"],"git_commit":execution["git_commit"],
        "first_error":first_error,"processing_seconds":execution.get("processing_seconds",NA),
        "operator_stopped":execution.get('operator_stopped',False),
        "artifact_directory":str(run.relative_to(REPO)),"next_action":"Stop after Phase 1; do not start Phase 2"}
    save(run/"phase1_result.json",result)
    with (REPO/"e2e_validation/execution_log.md").open("a",encoding="utf-8") as f:
        f.write(f"\n### Phase 1 finalized — {ids['timestamp']}\n```json\n{json.dumps(result,indent=2)}\n```\nIdentifiers (generated values only; unavailable values explicit):\n```json\n{json.dumps({k:v for k,v in ids.items() if k!='all_observed_uuid_fields'},indent=2,default=str)}\n```\nFull observed UUID inventory: {run.relative_to(REPO)}/identifiers.json.\n")
    with (REPO/"e2e_validation/CHECKPOINT.md").open("a",encoding="utf-8") as f:
        f.write(f"\n## Phase 1 — {ids['timestamp']}\n- Run {execution['run_id']}: {result['status']}.\n- Meeting {result['meeting_id']}; canonical {result['canonical_transcript_id']}.\n- First error: {result['first_error']}.\n- Evidence: {run.relative_to(REPO)}.\n- Phase 2 not started.\n")
    print(json.dumps(result,indent=2))
    return 0 if result["status"]=="VERIFIED" else 1

def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--run",type=Path,required=True)
    parser.add_argument('--mark-failed-oom',action='store_true')
    args=parser.parse_args(); run=args.run.resolve()
    if args.mark_failed_oom:
        original=json.loads((run/'execution.json').read_text())
        save(run/'execution_at_interruption.json',original)
        stop=json.loads((REPO/'e2e_validation/diagnostics'/f"{original['run_id']}_process_stop.json").read_text())
        original.update(status='BLOCKED',operator_stopped=True,execution_finished=stop['timestamp_utc'],
            error='Observed CUDA OOM; stopped exact validation process after automatic retries; CLI final response NOT AVAILABLE')
        save(run/'execution.json',original)
    return finalize(run,asyncio.run(readback(run,args.mark_failed_oom)))

if __name__=="__main__": sys.exit(main())
